---
driver:
  name: docker
  require_chef_omnibus: true
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 13

verifier:
  name: inspec

platforms:
  - name: debian-8
  - name: debian-9
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[git]
      - recipe[pentestenv]
    attributes:
      pentestenv:
        user: kitchen
        resources:
          /root/.pentestrc:
            instances:
              - kali
          /home/kitchen/.pentestrc:
            targets:
              - metasploitable3
